# Ingress-Ressource f√ºr Podinfo
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: a-benz-schalung
spec:
  ingressClassName: nginx
  rules:
  - host: a-team.k8s.schoeppi5.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: a-podinfo
            port:
              number: 80